/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fernandez.automatizacionenviodocumentos.sistemaenviodocumentosporwhatsapp;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author andro
 */
public class SenderApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SenderApp.class.getName());

    /**
     * Creates new form SenderApp
     */
    public SenderApp() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreCustomerTxt = new javax.swing.JTextField();
        nroTelefonoTxt = new javax.swing.JTextField();
        selectComprobanteBtn = new javax.swing.JButton();
        filePathTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hola, bienvenido al sistema de envio de mensajes de whatsapp");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Ingrese el nombre del cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("Ingrese el numero de telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setText("Seleccione el documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(nombreCustomerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, -1));
        getContentPane().add(nroTelefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        selectComprobanteBtn.setText("Seleccione comprobante");
        selectComprobanteBtn.addActionListener(this::selectComprobanteBtnActionPerformed);
        getContentPane().add(selectComprobanteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        filePathTxt.setEditable(false);
        filePathTxt.addActionListener(this::filePathTxtActionPerformed);
        getContentPane().add(filePathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, -1));

        jButton1.setText("Enviar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectComprobanteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComprobanteBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String userHome = System.getProperty("user.home");
        File downloadsDir = new File(userHome, "Downloads");
        
        if(downloadsDir.exists() && downloadsDir.isDirectory()){
            fc.setCurrentDirectory(downloadsDir);
        }
        else{
            fc.setCurrentDirectory(new File(userHome));
        }
        
        int response = fc.showOpenDialog(fc);
        
        if(response == JFileChooser.APPROVE_OPTION){
            File file = new File(fc.getSelectedFile().getPath());
            filePathTxt.setText(file.getPath());
        }
        
        
        
    }//GEN-LAST:event_selectComprobanteBtnActionPerformed

    private void filePathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreCliente = nombreCustomerTxt.getText().trim();
        String numeroCliente = nroTelefonoTxt.getText().trim();
        String filePath = filePathTxt.getText();
        
        if(nombreCliente.isEmpty() || numeroCliente.isEmpty() || filePath.isEmpty()){
            JOptionPane.showMessageDialog(null,"Completa todos los campos!", "ERROR_CAMPOS_VACIOS",JOptionPane.ERROR_MESSAGE);
        }
        
        File pdfComprobante = new File (filePath);
        
        try{
            WhatsappSender sender = new WhatsappSender();
            sender.sendMessage(numeroCliente, nombreCliente, pdfComprobante);
            sender.close();
            
            JOptionPane.showMessageDialog(null, "Mensaje enviado correctamente","ENVIO_EXITOSO",JOptionPane.OK_OPTION);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al enviar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SenderApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filePathTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreCustomerTxt;
    private javax.swing.JTextField nroTelefonoTxt;
    private javax.swing.JButton selectComprobanteBtn;
    // End of variables declaration//GEN-END:variables
}
